-- =============================================================================
-- DDL - Data Definition Language
-- Sistema: Gestión de Proyectos Monster
-- Base de datos: gestion_proyectos_monster
-- Motor: MySQL 8 / InnoDB
-- =============================================================================

CREATE DATABASE IF NOT EXISTS gestion_proyectos_monster
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE gestion_proyectos_monster;

-- ── Eliminar tablas existentes (orden inverso a las FK) ────────────────────────
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS XEUXP_USUPE;
DROP TABLE IF EXISTS XEUSU_USUAR;
DROP TABLE IF EXISTS XEOXP_OPCPE;
DROP TABLE IF EXISTS XEOPC_OPCIO;
DROP TABLE IF EXISTS XESIS_SISTE;
DROP TABLE IF EXISTS XEPER_PERFI;
DROP TABLE IF EXISTS XEEST_ESTAD;
DROP TABLE IF EXISTS GR_PEEMP_GEPRO;
DROP TABLE IF EXISTS GEPRO_PROYECT;
DROP TABLE IF EXISTS PEFIR_FIRMA;
DROP TABLE IF EXISTS PEEDU_EDUCACION;
DROP TABLE IF EXISTS PEFAM_FAMILI;
DROP TABLE IF EXISTS PEPRT_PARENT;
DROP TABLE IF EXISTS PEEMP_EMPLE;
DROP TABLE IF EXISTS PECAR_CARGO;
DROP TABLE IF EXISTS PEDEP_DEPAR;
DROP TABLE IF EXISTS PESEX_SEXO;
DROP TABLE IF EXISTS PEESC_ESTCIV;

SET FOREIGN_KEY_CHECKS = 1;

-- =============================================================================
-- TABLAS DE CATÁLOGO
-- =============================================================================

-- Departamentos
CREATE TABLE PEDEP_DEPAR (
    PEDEP_CODIGO    CHAR(3)      NOT NULL,
    PEDEP_DESCRI    VARCHAR(50)  NOT NULL,
    PRIMARY KEY (PEDEP_CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Sexo
CREATE TABLE PESEX_SEXO (
    PESEX_CODIGO    CHAR(1)      NOT NULL,
    PESEX_DESCRI    VARCHAR(50)  NOT NULL,
    PRIMARY KEY (PESEX_CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Estado civil
CREATE TABLE PEESC_ESTCIV (
    PEESC_CODIGO    CHAR(1)      NOT NULL,
    PEESC_DESCRI    VARCHAR(50)  NOT NULL,
    PRIMARY KEY (PEESC_CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Parentesco
CREATE TABLE PEPRT_PARENT (
    PEPRT_CODIGO    CHAR(6)      NOT NULL,
    PEPRT_TIPPAR    VARCHAR(50)  NOT NULL,
    PRIMARY KEY (PEPRT_CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Estado de usuario (Activo / Inactivo)
CREATE TABLE XEEST_ESTAD (
    XEEST_CODIGO    CHAR(1)      NOT NULL,
    XEEST_DESCRI    VARCHAR(50)  NOT NULL,
    PRIMARY KEY (XEEST_CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Sistemas (categorías de opciones del menú)
CREATE TABLE XESIS_SISTE (
    XESIS_CODIGO    CHAR(1)      NOT NULL,
    XESIS_DESCRI    VARCHAR(50)  NOT NULL,
    PRIMARY KEY (XESIS_CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =============================================================================
-- TABLAS PRINCIPALES
-- =============================================================================

-- Cargos (pertenecen a un departamento)
CREATE TABLE PECAR_CARGO (
    PEDEP_CODIGO        CHAR(3)     NOT NULL,
    PECAR_CODIGOCARGO   CHAR(3)     NOT NULL,
    PECAR_DESCRICARGO   VARCHAR(50) NOT NULL,
    PRIMARY KEY (PEDEP_CODIGO, PECAR_CODIGOCARGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Empleados
CREATE TABLE PEEMP_EMPLE (
    PEEMP_CODIGO        CHAR(6)      NOT NULL,
    PEC_PEDEP_CODIGO    CHAR(3)      NOT NULL,
    PECAR_CODIGOCARGO   CHAR(3)      NOT NULL,
    PEE_PEEMP_CODIGO    CHAR(6),
    PEDEP_CODIGO        CHAR(3),
    PEE_PEEMP_CODIGO2   CHAR(6),
    PESEX_CODIGO        CHAR(1)      NOT NULL,
    PED_PEDEP_CODIGO    CHAR(3)      NOT NULL,
    PEESC_CODIGO        CHAR(1),
    PED_PEDEP_CODIGO2   CHAR(3)      NOT NULL,
    PEEMP_APELLI        VARCHAR(50)  NOT NULL,
    PEEMP_NOMBRE        VARCHAR(50)  NOT NULL,
    PEEMP_FECNAC        DATE         NOT NULL,
    PEEMP_FECSAL        DATE         NOT NULL,
    PEEMP_DIREC         VARCHAR(200) NOT NULL,
    PEEMP_TELEF         VARCHAR(15)  NOT NULL,
    PEEMP_EMAIL         VARCHAR(100) NOT NULL,
    PEEMP_CEDULA        VARCHAR(10)  NOT NULL,
    PEEMP_FOTO          VARCHAR(100),
    PEEMP_CARFAM        NUMERIC(3,0) NOT NULL DEFAULT 0,
    PEEMP_PASAPO        VARCHAR(15)  NOT NULL,
    PEEMP_DISCAP        BLOB         NOT NULL,
    PRIMARY KEY (PEEMP_CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Educación / Formación del empleado
CREATE TABLE PEEDU_EDUCACION (
    PEEDU_CODIGO        CHAR(6)      NOT NULL,
    PEEMP_CODIGO        CHAR(6)      NOT NULL,
    PEEDU_TITULO        VARCHAR(100) NOT NULL,
    PEEDU_INSTITUCION   VARCHAR(100) NOT NULL,
    PEEDU_FECGRADO      DATE         NOT NULL,
    PEEDU_FECINI        DATE         NOT NULL,
    PRIMARY KEY (PEEDU_CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Firmas del empleado
CREATE TABLE PEFIR_FIRMA (
    PEFIR_CODIGO    CHAR(6)      NOT NULL,
    PEEMP_CODIGO    CHAR(6)      NOT NULL,
    PEFIR_DESCRIP   VARCHAR(200),
    PEFIR_RUTA      VARCHAR(200),
    PEFIR_FECCARGA  DATE         NOT NULL,
    PRIMARY KEY (PEFIR_CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Carga familiar del empleado
CREATE TABLE PEFAM_FAMILI (
    PEFAM_CODIGO    CHAR(6)     NOT NULL,
    PEEMP_CODIGO    CHAR(6)     NOT NULL,
    PEPRT_CODIGO    CHAR(6)     NOT NULL,
    PESEX_CODIGO    CHAR(1)     NOT NULL,
    PEFAM_NOMBRE    VARCHAR(50) NOT NULL,
    PEFAM_APELLI    VARCHAR(50) NOT NULL,
    PEFAM_FECNAC    DATE        NOT NULL,
    PEFAM_FECACT    DATE        NOT NULL,
    PRIMARY KEY (PEFAM_CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =============================================================================
-- TABLAS DE SEGURIDAD
-- =============================================================================

-- Perfiles de acceso
CREATE TABLE XEPER_PERFI (
    XEPER_CODIGO    CHAR(8)      NOT NULL,
    XEPER_DESCRI    VARCHAR(100) NOT NULL,
    XEPER_OBSER     TEXT,
    PRIMARY KEY (XEPER_CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Opciones del menú
CREATE TABLE XEOPC_OPCIO (
    XEOPC_CODIGO    CHAR(3)      NOT NULL,
    XESIS_CODIGO    CHAR(1)      NOT NULL,
    XEOPC_DESCRI    VARCHAR(100) NOT NULL,
    PRIMARY KEY (XEOPC_CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Asignación opciones ↔ perfiles
CREATE TABLE XEOXP_OPCPE (
    XEPER_CODIGO    CHAR(8) NOT NULL,
    XEOPC_CODIGO    CHAR(3) NOT NULL,
    XEOXP_FECASI   DATE    NOT NULL,
    XEOXP_FECRET   DATE,
    PRIMARY KEY (XEPER_CODIGO, XEOPC_CODIGO, XEOXP_FECASI)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Usuarios del sistema
CREATE TABLE XEUSU_USUAR (
    PEEMP_CODIGO    CHAR(6)      NOT NULL,
    XEUSU_PASWD     VARCHAR(64)  NOT NULL,
    XEEST_CODIGO    CHAR(1)      NOT NULL,
    XEUSU_FECCRE    DATETIME     NOT NULL,
    XEUSU_FECMOD    DATETIME     NOT NULL,
    XEUSU_PIEFIR    VARCHAR(100) NOT NULL,
    PRIMARY KEY (PEEMP_CODIGO, XEUSU_PASWD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Historial usuario ↔ perfil
CREATE TABLE XEUXP_USUPE (
    XEPER_CODIGO    CHAR(8)     NOT NULL,
    PEEMP_CODIGO    CHAR(6)     NOT NULL,
    XEUSU_PASWD     VARCHAR(64) NOT NULL,
    XEUXP_FECASI   DATE        NOT NULL,
    XEUXP_FECRET   DATE,
    PRIMARY KEY (XEPER_CODIGO, PEEMP_CODIGO, XEUSU_PASWD, XEUXP_FECASI)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =============================================================================
-- TABLAS DE PROYECTOS
-- =============================================================================

-- Proyectos
CREATE TABLE GEPRO_PROYECT (
    GEPRO_CODIGO    CHAR(3)       NOT NULL,
    PEDEP_CODIGO    CHAR(3),
    GEPRO_NOMBRE    VARCHAR(100)  NOT NULL,
    GEPRO_DESCRI    VARCHAR(255),
    GEPRO_PRESUP    DECIMAL(12,2) NOT NULL DEFAULT 0,   -- Presupuesto (costo planificado)
    GEPRO_GASTO     DECIMAL(12,2) NOT NULL DEFAULT 0,   -- Gasto acumulado (costo real)
    GEPRO_FECINI    DATE,                               -- Fecha de inicio
    GEPRO_FECFIN    DATE,                               -- Fecha de fin estimada
    GEPRO_AVANCE    INT           NOT NULL DEFAULT 0,   -- Porcentaje de avance 0-100
    GEPRO_ESTADO    VARCHAR(20)   NOT NULL DEFAULT 'PLANIFICADO', -- PLANIFICADO | EN_PROGRESO | COMPLETADO | CANCELADO
    GEPRO_RECURS    VARCHAR(255),                       -- Recursos del proyecto (materiales, licencias, equipos)
    PRIMARY KEY (GEPRO_CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Asignación empleados ↔ proyectos
CREATE TABLE GR_PEEMP_GEPRO (
    PEEMP_CODIGO    CHAR(6) NOT NULL,
    GEPRO_CODIGO    CHAR(3) NOT NULL,
    PRIMARY KEY (PEEMP_CODIGO, GEPRO_CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =============================================================================
-- CLAVES FORÁNEAS
-- =============================================================================

-- PECAR_CARGO
ALTER TABLE PECAR_CARGO
    ADD CONSTRAINT FK_PR_PEDEP_PECAR
        FOREIGN KEY (PEDEP_CODIGO) REFERENCES PEDEP_DEPAR (PEDEP_CODIGO)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

-- PEEMP_EMPLE
ALTER TABLE PEEMP_EMPLE
    ADD CONSTRAINT FK_PR_PECAR_PEEMP
        FOREIGN KEY (PEC_PEDEP_CODIGO, PECAR_CODIGOCARGO)
        REFERENCES PECAR_CARGO (PEDEP_CODIGO, PECAR_CODIGOCARGO)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PEEMP_EMPLE
    ADD CONSTRAINT FK_EMPLE_DEPART
        FOREIGN KEY (PEDEP_CODIGO) REFERENCES PEDEP_DEPAR (PEDEP_CODIGO)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PEEMP_EMPLE
    ADD CONSTRAINT FK_EMPLE_SUP__EMPLE_NO_SUP_
        FOREIGN KEY (PEE_PEEMP_CODIGO) REFERENCES PEEMP_EMPLE (PEEMP_CODIGO)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PEEMP_EMPLE
    ADD CONSTRAINT FK_PR_PEEMP_PEEMP
        FOREIGN KEY (PEE_PEEMP_CODIGO2) REFERENCES PEEMP_EMPLE (PEEMP_CODIGO)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PEEMP_EMPLE
    ADD CONSTRAINT FK_PR_PESEX_PEEMP
        FOREIGN KEY (PESEX_CODIGO) REFERENCES PESEX_SEXO (PESEX_CODIGO)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PEEMP_EMPLE
    ADD CONSTRAINT FK_RE_PEESC_PEEMP
        FOREIGN KEY (PEESC_CODIGO) REFERENCES PEESC_ESTCIV (PEESC_CODIGO)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PEEMP_EMPLE
    ADD CONSTRAINT FK_GR_PEEMP_PEDEP
        FOREIGN KEY (PED_PEDEP_CODIGO) REFERENCES PEDEP_DEPAR (PEDEP_CODIGO)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PEEMP_EMPLE
    ADD CONSTRAINT FK_PR_PEDEP_PEEMP
        FOREIGN KEY (PED_PEDEP_CODIGO2) REFERENCES PEDEP_DEPAR (PEDEP_CODIGO)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

-- PEEDU_EDUCACION
ALTER TABLE PEEDU_EDUCACION
    ADD CONSTRAINT FK_PR_PEEMP_PEEDU
        FOREIGN KEY (PEEMP_CODIGO) REFERENCES PEEMP_EMPLE (PEEMP_CODIGO)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

-- PEFIR_FIRMA
ALTER TABLE PEFIR_FIRMA
    ADD CONSTRAINT FK_PR_PEEMP_PEFIR
        FOREIGN KEY (PEEMP_CODIGO) REFERENCES PEEMP_EMPLE (PEEMP_CODIGO)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

-- PEFAM_FAMILI
ALTER TABLE PEFAM_FAMILI
    ADD CONSTRAINT FK_PR_PEEMP_PEFAM
        FOREIGN KEY (PEEMP_CODIGO) REFERENCES PEEMP_EMPLE (PEEMP_CODIGO)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PEFAM_FAMILI
    ADD CONSTRAINT FK_PR_PEPRT_PEFAM
        FOREIGN KEY (PEPRT_CODIGO) REFERENCES PEPRT_PARENT (PEPRT_CODIGO)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PEFAM_FAMILI
    ADD CONSTRAINT FK_PR_PESEX_PEFAM
        FOREIGN KEY (PESEX_CODIGO) REFERENCES PESEX_SEXO (PESEX_CODIGO)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

-- XEOPC_OPCIO
ALTER TABLE XEOPC_OPCIO
    ADD CONSTRAINT FK_XR_XESIS_XEOPC
        FOREIGN KEY (XESIS_CODIGO) REFERENCES XESIS_SISTE (XESIS_CODIGO)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

-- XEOXP_OPCPE
ALTER TABLE XEOXP_OPCPE
    ADD CONSTRAINT FK_XR_XEPER_XEOXP
        FOREIGN KEY (XEPER_CODIGO) REFERENCES XEPER_PERFI (XEPER_CODIGO)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE XEOXP_OPCPE
    ADD CONSTRAINT FK_XR_XEOPC_XEOXP
        FOREIGN KEY (XEOPC_CODIGO) REFERENCES XEOPC_OPCIO (XEOPC_CODIGO)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

-- XEUSU_USUAR
ALTER TABLE XEUSU_USUAR
    ADD CONSTRAINT FK_XR_PEEMP_XEUSU
        FOREIGN KEY (PEEMP_CODIGO) REFERENCES PEEMP_EMPLE (PEEMP_CODIGO)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE XEUSU_USUAR
    ADD CONSTRAINT FK_XR_XEEST_XEUSU
        FOREIGN KEY (XEEST_CODIGO) REFERENCES XEEST_ESTAD (XEEST_CODIGO)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

-- XEUXP_USUPE
ALTER TABLE XEUXP_USUPE
    ADD CONSTRAINT FK_XR_XEPER_XEUXP
        FOREIGN KEY (XEPER_CODIGO) REFERENCES XEPER_PERFI (XEPER_CODIGO)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE XEUXP_USUPE
    ADD CONSTRAINT FK_XR_XEUSU_XEUXP
        FOREIGN KEY (PEEMP_CODIGO, XEUSU_PASWD)
        REFERENCES XEUSU_USUAR (PEEMP_CODIGO, XEUSU_PASWD)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

-- GEPRO_PROYECT
ALTER TABLE GEPRO_PROYECT
    ADD CONSTRAINT FK_GR_PEDEP_GEPRO
        FOREIGN KEY (PEDEP_CODIGO) REFERENCES PEDEP_DEPAR (PEDEP_CODIGO)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

-- GR_PEEMP_GEPRO
ALTER TABLE GR_PEEMP_GEPRO
    ADD CONSTRAINT FK_GR_PEEMP_GEPRO
        FOREIGN KEY (GEPRO_CODIGO) REFERENCES GEPRO_PROYECT (GEPRO_CODIGO)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE GR_PEEMP_GEPRO
    ADD CONSTRAINT FK_TIENE
        FOREIGN KEY (PEEMP_CODIGO) REFERENCES PEEMP_EMPLE (PEEMP_CODIGO)
        ON DELETE RESTRICT ON UPDATE RESTRICT;
