CREATE DATABASE IF NOT EXISTS gestion_proyectos_monster
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE gestion_proyectos_monster;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS PEFIR_FIRMA;
DROP TABLE IF EXISTS PEEDU_EDUCACION;
DROP TABLE IF EXISTS GEPRO_PROYECT;
DROP TABLE IF EXISTS GR_PEEMP_GEPRO;
DROP TABLE IF EXISTS PECAR_CARGO;
DROP TABLE IF EXISTS PEDEP_DEPAR;
DROP TABLE IF EXISTS PEEMP_EMPLE;
DROP TABLE IF EXISTS PEESC_ESTCIV;
DROP TABLE IF EXISTS PEFAM_FAMILI;
DROP TABLE IF EXISTS PEPRT_PARENT;
DROP TABLE IF EXISTS PESEX_SEXO;
DROP TABLE IF EXISTS XEEST_ESTAD;
DROP TABLE IF EXISTS XEOPC_OPCIO;
DROP TABLE IF EXISTS XEOXP_OPCPE;
DROP TABLE IF EXISTS XEPER_PERFI;
DROP TABLE IF EXISTS XESIS_SISTE;
DROP TABLE IF EXISTS XEUSU_USUAR;
DROP TABLE IF EXISTS XEUXP_USUPE;

SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE PEDEP_DEPAR (
   PEDEP_CODIGO         CHAR(3) NOT NULL,
   PEDEP_DESCRI         VARCHAR(50) NOT NULL,
   PRIMARY KEY (PEDEP_CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE GEPRO_PROYECT (
   GEPRO_CODIGO         CHAR(3) NOT NULL,
   PEDEP_CODIGO         CHAR(3),
   GEPRO_NOMBRE         VARCHAR(50) NOT NULL,
   PRIMARY KEY (GEPRO_CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE GR_PEEMP_GEPRO (
   PEEMP_CODIGO         CHAR(6) NOT NULL,
   GEPRO_CODIGO         CHAR(3) NOT NULL,
   PRIMARY KEY (PEEMP_CODIGO, GEPRO_CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE PECAR_CARGO (
   PEDEP_CODIGO         CHAR(3) NOT NULL,
   PECAR_CODIGOCARGO    CHAR(3) NOT NULL,
   PECAR_DESCRICARGO    VARCHAR(50) NOT NULL,
   PRIMARY KEY (PEDEP_CODIGO, PECAR_CODIGOCARGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE PEEMP_EMPLE (
   PEEMP_CODIGO         CHAR(6) NOT NULL,
   PEC_PEDEP_CODIGO     CHAR(3) NOT NULL,
   PECAR_CODIGOCARGO    CHAR(3) NOT NULL,
   PEE_PEEMP_CODIGO     CHAR(6),
   PEDEP_CODIGO         CHAR(3),
   PEE_PEEMP_CODIGO2    CHAR(6),
   PESEX_CODIGO         CHAR(1) NOT NULL,
   PED_PEDEP_CODIGO     CHAR(3) NOT NULL,
   PEESC_CODIGO         CHAR(1),
   PED_PEDEP_CODIGO2    CHAR(3) NOT NULL,
   PEEMP_APELLI         VARCHAR(50) NOT NULL,
   PEEMP_NOMBRE         VARCHAR(50) NOT NULL,
   PEEMP_FECNAC         DATE NOT NULL,
   PEEMP_FECSAL         DATE NOT NULL,
   PEEMP_DIREC          VARCHAR(200) NOT NULL,
   PEEMP_TELEF          VARCHAR(15) NOT NULL,
   PEEMP_EMAIL          VARCHAR(100) NOT NULL,
   PEEMP_CEDULA         VARCHAR(10) NOT NULL,
   PEEMP_FOTO           VARCHAR(100),
   PEEMP_CARFAM         NUMERIC(3,0) NOT NULL,
   PEEMP_PASAPO         VARCHAR(15) NOT NULL,
   PEEMP_DISCAP         BLOB NOT NULL,
   PRIMARY KEY (PEEMP_CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE PEEDU_EDUCACION (
   PEEDU_CODIGO         CHAR(6) NOT NULL,
   PEEMP_CODIGO         CHAR(6) NOT NULL,
   PEEDU_TITULO         VARCHAR(100) NOT NULL,
   PEEDU_INSTITUCION    VARCHAR(100) NOT NULL,
   PEEDU_FECGRADO       DATE NOT NULL,
   PEEDU_FECINI         DATE NOT NULL,
   PRIMARY KEY (PEEDU_CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE PEFIR_FIRMA (
   PEFIR_CODIGO         CHAR(6) NOT NULL,
   PEEMP_CODIGO         CHAR(6) NOT NULL,
   PEFIR_DESCRIP        VARCHAR(200),
   PEFIR_RUTA           VARCHAR(200),
   PEFIR_FECCARGA       DATE NOT NULL,
   PRIMARY KEY (PEFIR_CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE PEESC_ESTCIV (
   PEESC_CODIGO         CHAR(1) NOT NULL,
   PEESC_DESCRI         VARCHAR(50) NOT NULL,
   PRIMARY KEY (PEESC_CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE PEFAM_FAMILI (
   PEFAM_CODIGO         CHAR(6) NOT NULL,
   PEEMP_CODIGO         CHAR(6) NOT NULL,
   PEPRT_CODIGO         CHAR(6) NOT NULL,
   PESEX_CODIGO         CHAR(1) NOT NULL,
   PEFAM_NOMBRE         VARCHAR(50) NOT NULL,
   PEFAM_APELLI         VARCHAR(50) NOT NULL,
   PEFAM_FECNAC         DATE NOT NULL,
   PEFAM_FECACT         DATE NOT NULL,
   PRIMARY KEY (PEFAM_CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE PEPRT_PARENT (
   PEPRT_CODIGO         CHAR(6) NOT NULL,
   PEPRT_TIPPAR         VARCHAR(50) NOT NULL,
   PRIMARY KEY (PEPRT_CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE PESEX_SEXO (
   PESEX_CODIGO         CHAR(1) NOT NULL,
   PESEX_DESCRI         VARCHAR(50) NOT NULL,
   PRIMARY KEY (PESEX_CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE XEEST_ESTAD (
   XEEST_CODIGO         CHAR(1) NOT NULL,
   XEEST_DESCRI         VARCHAR(50) NOT NULL,
   PRIMARY KEY (XEEST_CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE XEOPC_OPCIO (
   XEOPC_CODIGO         CHAR(3) NOT NULL,
   XESIS_CODIGO         CHAR(1) NOT NULL,
   XEOPC_DESCRI         VARCHAR(100) NOT NULL,
   PRIMARY KEY (XEOPC_CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE XEOXP_OPCPE (
   XEPER_CODIGO         CHAR(8) NOT NULL,
   XEOPC_CODIGO         CHAR(3) NOT NULL,
   XEOXP_FECASI         DATE NOT NULL,
   XEOXP_FECRET         DATE,
   PRIMARY KEY (XEPER_CODIGO, XEOPC_CODIGO, XEOXP_FECASI)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE XEPER_PERFI (
   XEPER_CODIGO         CHAR(8) NOT NULL,
   XEPER_DESCRI         VARCHAR(100) NOT NULL,
   XEPER_OBSER          TEXT,
   PRIMARY KEY (XEPER_CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE XESIS_SISTE (
   XESIS_CODIGO         CHAR(1) NOT NULL,
   XESIS_DESCRI         VARCHAR(50) NOT NULL,
   PRIMARY KEY (XESIS_CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE XEUSU_USUAR (
   PEEMP_CODIGO         CHAR(6) NOT NULL,
   XEUSU_PASWD          VARCHAR(64) NOT NULL,
   XEEST_CODIGO         CHAR(1) NOT NULL,
   XEUSU_FECCRE         DATETIME NOT NULL,
   XEUSU_FECMOD         DATETIME NOT NULL,
   XEUSU_PIEFIR         VARCHAR(100) NOT NULL,
   PRIMARY KEY (PEEMP_CODIGO, XEUSU_PASWD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE XEUXP_USUPE (
   XEPER_CODIGO         CHAR(8) NOT NULL,
   PEEMP_CODIGO         CHAR(6) NOT NULL,
   XEUSU_PASWD          VARCHAR(64) NOT NULL,
   XEUXP_FECASI         DATE NOT NULL,
   XEUXP_FECRET         DATE,
   PRIMARY KEY (XEPER_CODIGO, PEEMP_CODIGO, XEUSU_PASWD, XEUXP_FECASI)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE GEPRO_PROYECT ADD CONSTRAINT FK_GR_PEDEP_GEPRO FOREIGN KEY (PEDEP_CODIGO)
      REFERENCES PEDEP_DEPAR (PEDEP_CODIGO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE GR_PEEMP_GEPRO ADD CONSTRAINT FK_GR_PEEMP_GEPRO FOREIGN KEY (GEPRO_CODIGO)
      REFERENCES GEPRO_PROYECT (GEPRO_CODIGO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE GR_PEEMP_GEPRO ADD CONSTRAINT FK_TIENE FOREIGN KEY (PEEMP_CODIGO)
      REFERENCES PEEMP_EMPLE (PEEMP_CODIGO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PECAR_CARGO ADD CONSTRAINT FK_PR_PEDEP_PECAR FOREIGN KEY (PEDEP_CODIGO)
      REFERENCES PEDEP_DEPAR (PEDEP_CODIGO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PEEMP_EMPLE ADD CONSTRAINT FK_EMPLE_DEPART FOREIGN KEY (PEDEP_CODIGO)
      REFERENCES PEDEP_DEPAR (PEDEP_CODIGO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PEEMP_EMPLE ADD CONSTRAINT FK_EMPLE_SUP__EMPLE_NO_SUP_ FOREIGN KEY (PEE_PEEMP_CODIGO)
      REFERENCES PEEMP_EMPLE (PEEMP_CODIGO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PEEMP_EMPLE ADD CONSTRAINT FK_GR_PEEMP_PEDEP FOREIGN KEY (PED_PEDEP_CODIGO)
      REFERENCES PEDEP_DEPAR (PEDEP_CODIGO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PEEMP_EMPLE ADD CONSTRAINT FK_PR_PECAR_PEEMP FOREIGN KEY (PEC_PEDEP_CODIGO, PECAR_CODIGOCARGO)
      REFERENCES PECAR_CARGO (PEDEP_CODIGO, PECAR_CODIGOCARGO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PEEMP_EMPLE ADD CONSTRAINT FK_PR_PEDEP_PEEMP FOREIGN KEY (PED_PEDEP_CODIGO2)
      REFERENCES PEDEP_DEPAR (PEDEP_CODIGO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PEEMP_EMPLE ADD CONSTRAINT FK_PR_PEEMP_PEEMP FOREIGN KEY (PEE_PEEMP_CODIGO2)
      REFERENCES PEEMP_EMPLE (PEEMP_CODIGO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PEEMP_EMPLE ADD CONSTRAINT FK_PR_PESEX_PEEMP FOREIGN KEY (PESEX_CODIGO)
      REFERENCES PESEX_SEXO (PESEX_CODIGO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PEEMP_EMPLE ADD CONSTRAINT FK_RE_PEESC_PEEMP FOREIGN KEY (PEESC_CODIGO)
      REFERENCES PEESC_ESTCIV (PEESC_CODIGO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PEFAM_FAMILI ADD CONSTRAINT FK_PR_PEEMP_PEFAM FOREIGN KEY (PEEMP_CODIGO)
      REFERENCES PEEMP_EMPLE (PEEMP_CODIGO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PEFAM_FAMILI ADD CONSTRAINT FK_PR_PEPRT_PEFAM FOREIGN KEY (PEPRT_CODIGO)
      REFERENCES PEPRT_PARENT (PEPRT_CODIGO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PEFAM_FAMILI ADD CONSTRAINT FK_PR_PESEX_PEFAM FOREIGN KEY (PESEX_CODIGO)
      REFERENCES PESEX_SEXO (PESEX_CODIGO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PEEDU_EDUCACION ADD CONSTRAINT FK_PR_PEEMP_PEEDU FOREIGN KEY (PEEMP_CODIGO)
      REFERENCES PEEMP_EMPLE (PEEMP_CODIGO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PEFIR_FIRMA ADD CONSTRAINT FK_PR_PEEMP_PEFIR FOREIGN KEY (PEEMP_CODIGO)
      REFERENCES PEEMP_EMPLE (PEEMP_CODIGO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE XEOPC_OPCIO ADD CONSTRAINT FK_XR_XESIS_XEOPC FOREIGN KEY (XESIS_CODIGO)
      REFERENCES XESIS_SISTE (XESIS_CODIGO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE XEOXP_OPCPE ADD CONSTRAINT FK_XR_XEOPC_XEOXP FOREIGN KEY (XEOPC_CODIGO)
      REFERENCES XEOPC_OPCIO (XEOPC_CODIGO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE XEOXP_OPCPE ADD CONSTRAINT FK_XR_XEPER_XEOXP FOREIGN KEY (XEPER_CODIGO)
      REFERENCES XEPER_PERFI (XEPER_CODIGO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE XEUSU_USUAR ADD CONSTRAINT FK_XR_PEEMP_XEUSU FOREIGN KEY (PEEMP_CODIGO)
      REFERENCES PEEMP_EMPLE (PEEMP_CODIGO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE XEUSU_USUAR ADD CONSTRAINT FK_XR_XEEST_XEUSU FOREIGN KEY (XEEST_CODIGO)
      REFERENCES XEEST_ESTAD (XEEST_CODIGO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE XEUXP_USUPE ADD CONSTRAINT FK_XR_XEPER_XEUXP FOREIGN KEY (XEPER_CODIGO)
      REFERENCES XEPER_PERFI (XEPER_CODIGO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE XEUXP_USUPE ADD CONSTRAINT FK_XR_XEUSU_XEUXP FOREIGN KEY (PEEMP_CODIGO, XEUSU_PASWD)
      REFERENCES XEUSU_USUAR (PEEMP_CODIGO, XEUSU_PASWD) ON DELETE RESTRICT ON UPDATE RESTRICT;

INSERT INTO PEDEP_DEPAR (PEDEP_CODIGO, PEDEP_DESCRI) VALUES
('001', 'Sistemas'),
('002', 'Talento Humano'),
('003', 'Proyectos'),
('004', 'Finanzas');

INSERT INTO PESEX_SEXO (PESEX_CODIGO, PESEX_DESCRI) VALUES
('M', 'Masculino'),
('F', 'Femenino'),
('H', 'Hermafrodita');

INSERT INTO PEESC_ESTCIV (PEESC_CODIGO, PEESC_DESCRI) VALUES
('S', 'Soltero'),
('C', 'Casado');

INSERT INTO PEPRT_PARENT (PEPRT_CODIGO, PEPRT_TIPPAR) VALUES
('PRT001', 'Padre'),
('PRT002', 'Madre'),
('PRT003', 'Conyuge'),
('PRT004', 'Hijo/a');

INSERT INTO XEEST_ESTAD (XEEST_CODIGO, XEEST_DESCRI) VALUES
('A', 'Activo'),
('I', 'Inactivo');

INSERT INTO PECAR_CARGO (PEDEP_CODIGO, PECAR_CODIGOCARGO, PECAR_DESCRICARGO) VALUES
('001', 'ADM', 'Administrador'),
('002', 'ANA', 'Analista'),
('003', 'JPR', 'Jefe de proyecto'),
('003', 'EMP', 'Empleado');

-- ── Sistemas (categorías de opciones) ───────────────────────────────────────
INSERT INTO XESIS_SISTE (XESIS_CODIGO, XESIS_DESCRI) VALUES
('S', 'Seguridad'),
('H', 'Recursos Humanos'),
('P', 'Proyectos');

-- ── Opciones de menú (16 opciones que controlan la navegación) ───────────────
-- Códigos usados en DAOOPCIONES como constantes OPC_*
INSERT INTO XEOPC_OPCIO (XEOPC_CODIGO, XESIS_CODIGO, XEOPC_DESCRI) VALUES
('001', 'S', 'Inicio'),
('002', 'S', 'Gestión de usuarios'),
('003', 'H', 'Gestión de departamentos'),
('004', 'S', 'Asignación de perfiles'),
('005', 'S', 'Gestión de contraseñas'),
('006', 'S', 'Asignar opciones al perfil'),
('007', 'S', 'Cambiar contraseña propia'),
('008', 'H', 'Gestión de personal'),
('009', 'H', 'Gestionar familiares'),
('010', 'H', 'Organigrama'),
('011', 'H', 'Reporte de personal'),
('012', 'P', 'Gestión de proyectos'),
('013', 'P', 'Asignación de personal a proyectos'),
('014', 'P', 'Aprobación de horas'),
('015', 'P', 'Reportes de horas'),
('016', 'P', 'Registrar horas reales'),
('017', 'S', 'Gestión de perfiles'),
('018', 'P', 'Reporte de gestión de proyectos');

-- ── Perfiles de acceso ───────────────────────────────────────────────────────
INSERT INTO XEPER_PERFI (XEPER_CODIGO, XEPER_DESCRI, XEPER_OBSER) VALUES
('PERF0001', 'Administrador',        'Acceso completo al sistema'),
('PERF0002', 'RR. HH.',              'Administración de empleados, familiares y reportes de personal'),
('PERF0003', 'Jefe de Departamento', 'Gestión de proyectos, asignaciones, aprobación y reportes de horas'),
('PERF0004', 'Empleado',             'Registro de horas reales en proyectos asignados');

-- ── Asignación opciones ↔ perfiles ──────────────────────────────────────────
-- PERF0001 Administrador → TODAS las opciones
INSERT INTO XEOXP_OPCPE (XEPER_CODIGO, XEOPC_CODIGO, XEOXP_FECASI, XEOXP_FECRET) VALUES
('PERF0001', '001', '2026-05-14', NULL),
('PERF0001', '002', '2026-05-14', NULL),
('PERF0001', '003', '2026-05-14', NULL),
('PERF0001', '004', '2026-05-14', NULL),
('PERF0001', '005', '2026-05-14', NULL),
('PERF0001', '006', '2026-05-14', NULL),
('PERF0001', '007', '2026-05-14', NULL),
('PERF0001', '008', '2026-05-14', NULL),
('PERF0001', '009', '2026-05-14', NULL),
('PERF0001', '010', '2026-05-14', NULL),
('PERF0001', '011', '2026-05-14', NULL),
('PERF0001', '012', '2026-05-14', NULL),
('PERF0001', '013', '2026-05-14', NULL),
('PERF0001', '014', '2026-05-14', NULL),
('PERF0001', '015', '2026-05-14', NULL),
('PERF0001', '016', '2026-05-14', NULL),
('PERF0001', '017', '2026-05-14', NULL),
-- PERF0002 RR.HH. → Personal + cambiar clave propia
('PERF0002', '001', '2026-05-14', NULL),
('PERF0002', '003', '2026-05-14', NULL),
('PERF0002', '007', '2026-05-14', NULL),
('PERF0002', '008', '2026-05-14', NULL),
('PERF0002', '009', '2026-05-14', NULL),
('PERF0002', '010', '2026-05-14', NULL),
('PERF0002', '011', '2026-05-14', NULL),
-- PERF0003 Jefe Departamento → Proyectos + cambiar clave propia
('PERF0003', '001', '2026-05-14', NULL),
('PERF0003', '007', '2026-05-14', NULL),
('PERF0003', '012', '2026-05-14', NULL),
('PERF0003', '013', '2026-05-14', NULL),
('PERF0003', '014', '2026-05-14', NULL),
('PERF0003', '015', '2026-05-14', NULL),
('PERF0003', '016', '2026-05-14', NULL),
-- PERF0004 Empleado → Registrar horas + cambiar clave propia
('PERF0004', '001', '2026-05-14', NULL),
('PERF0004', '007', '2026-05-14', NULL),
('PERF0004', '016', '2026-05-14', NULL),
-- PERF0001 y PERF0003 → Reporte de gestión de proyectos (opción 018)
('PERF0001', '018', '2026-05-14', NULL),
('PERF0003', '018', '2026-05-14', NULL);

INSERT INTO PEEMP_EMPLE (
    PEEMP_CODIGO, PEC_PEDEP_CODIGO, PECAR_CODIGOCARGO, PEE_PEEMP_CODIGO,
    PEDEP_CODIGO, PEE_PEEMP_CODIGO2, PESEX_CODIGO, PED_PEDEP_CODIGO,
    PEESC_CODIGO, PED_PEDEP_CODIGO2, PEEMP_APELLI, PEEMP_NOMBRE,
    PEEMP_FECNAC, PEEMP_FECSAL, PEEMP_DIREC, PEEMP_TELEF, PEEMP_EMAIL,
    PEEMP_CEDULA, PEEMP_FOTO, PEEMP_CARFAM, PEEMP_PASAPO, PEEMP_DISCAP
) VALUES
('EMP001', '001', 'ADM', NULL, '001', NULL, 'M', '001', 'S', '001',
 'Padilla', 'Marco', '2000-01-15', '2099-12-31', 'Quito', '0999999991',
 'marco.padilla@monster.edu', '1711111111', NULL, 0, 'P001', X'00'),
('EMP002', '002', 'ANA', NULL, '002', NULL, 'F', '002', 'S', '002',
 'Toscano', 'Edgar', '2001-03-20', '2099-12-31', 'Quito', '0999999992',
 'edgar.toscano@monster.edu', '1722222222', NULL, 0, 'P002', X'00'),
('EMP003', '003', 'JPR', NULL, '003', NULL, 'M', '003', 'C', '003',
 'Sigcha', 'Kenned', '1999-07-10', '2099-12-31', 'Quito', '0999999993',
 'kenned.sigcha@monster.edu', '1733333333', NULL, 0, 'P003', X'00'),
('EMP004', '003', 'EMP', NULL, '003', NULL, 'F', '003', 'S', '003',
 'Benitez', 'Carla', '2002-11-05', '2099-12-31', 'Quito', '0999999994',
 'carla.benitez@monster.edu', '1744444444', NULL, 0, 'P004', X'00');

INSERT INTO XEUSU_USUAR (
    PEEMP_CODIGO, XEUSU_PASWD, XEEST_CODIGO, XEUSU_FECCRE, XEUSU_FECMOD, XEUSU_PIEFIR
) VALUES
('EMP001', '0044987cdf13f5acc8daab9eced9435743e8a013f87ef561dea3bee7c2196696', 'A', NOW(), NOW(), 'Administrador del sistema'),
('EMP002', 'c0abb0c3a0c510bff5cefab61b90588865c17e4dcc22d560ff9f6d47314c0b67', 'A', NOW(), NOW(), 'Director de Recursos Humanos'),
('EMP003', '975ee79f5b5894888012afd43c3548628d479e3d75348fccb5c2bf3cff280831', 'A', NOW(), NOW(), 'Jefe de Departamento'),
('EMP004', 'c5ffd4a5cf1b0b2941f56283c4b34be0279ec2635aaa8417feb9a6bf137f1c42', 'A', NOW(), NOW(), 'Empleado operativo');

INSERT INTO XEUXP_USUPE (XEPER_CODIGO, PEEMP_CODIGO, XEUSU_PASWD, XEUXP_FECASI, XEUXP_FECRET) VALUES
('PERF0001', 'EMP001', '0044987cdf13f5acc8daab9eced9435743e8a013f87ef561dea3bee7c2196696', '2026-05-14', NULL),
('PERF0002', 'EMP002', 'c0abb0c3a0c510bff5cefab61b90588865c17e4dcc22d560ff9f6d47314c0b67', '2026-05-14', NULL),
('PERF0003', 'EMP003', '975ee79f5b5894888012afd43c3548628d479e3d75348fccb5c2bf3cff280831', '2026-05-14', NULL),
('PERF0004', 'EMP004', 'c5ffd4a5cf1b0b2941f56283c4b34be0279ec2635aaa8417feb9a6bf137f1c42', '2026-05-14', NULL);

INSERT INTO GEPRO_PROYECT (GEPRO_CODIGO, PEDEP_CODIGO, GEPRO_NOMBRE) VALUES
('P01', '003', 'Sistema de Gestión de Proyectos');

INSERT INTO GR_PEEMP_GEPRO (PEEMP_CODIGO, GEPRO_CODIGO) VALUES
('EMP001', 'P01'),
('EMP002', 'P01'),
('EMP003', 'P01'),
('EMP004', 'P01');
